server.port=8083
spring.application.name=paiement_service

spring.datasource.url=jdbc:postgresql://localhost:5432/fitunity_payment
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.fitunity.paiement_service=DEBUG
# JWT
jwt.secret=08efa6a9-3d9b-4b18-bd11-0e0f85654d00-4faf5919-1c5f-4782-9f44-cbb4bc48390b
jwt.issuer=fitunity-auth
jwt.audience=fitunity-client
# Stripe
stripe.api.key=sk_test_51TQ35YGwWBTi3VGnSz5RD7246SCGHdamDL64kawcDURFZoOrK77WeXOOK35rhkAc1VySffJl4bE0zCvTJqYoR6NP00UdHJUf7C
stripe.publishable.key=pk_test_51TQ35YGwWBTi3VGnDg6ZjVAt2o3LQfnvEd8uPhasWyjAcUdNB0Z9BJ15H0eh9Uap6M8ywGHUlHqd97CVwqoWibJc00DFafeivg
# PayPal
paypal.client.id=VOTRE_CLIENT_ID_PAYPAL
paypal.client.secret=VOTRE_CLIENT_SECRET_PAYPAL
paypal.mode=sandbox
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest